apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: animals 

spec:
 volumes:
   - name: app-storage
     emptyDir: {}
 containers:
 - name: app1 
   image: supergiantkir/animals:bear 
   ports: 
   - containerPort: 80
   volumeMounts:
    - name: app-storage
      mountPath: /storage

 - name: app2
   image: supergiantkir/animals:moose
   ports: 
   - containerPort: 80
   volumeMounts:
    - name: app-storage
      mountPath: /storage